### ISSUE TITLE
Error if name contains `$`

### ISSUE THREAD

**Issue by Saul-Mirone** [marijnh/builddocs#18]
If the name of variables and parameters contains `$`, an error will be thrown.

For example: `$Slice`.

**Comment by marijnh** [comment]
Are you sure? This is being used to build [the prosemirror docs](https://prosemirror.net/docs/ref/#state.Selection.$anchor), which have a number of variables with `$` in their name.

**Comment by Saul-Mirone** [comment]
Yeah I'm sure about this. It only appears when I use top level API starts with `$` in markdown template which means I need to declare the Item with `@$Slice`.

I think it's related to here:
https://github.com/marijnh/builddocs/blob/master/src/builddocs.js#L22

Seems the regex here only recoganize item names starts with `\w`, which means `$` will out of this scope.
When I replace the `\w` with `(\w|\$)`, seems everything works fine.
