### ISSUE TITLE
How to represent accessors?

### ISSUE THREAD

**Issue by adrianheine** [marijnh/builddocs#5]
Should `get x() { return 0 }` be `readonly x: number`, and `get x() { return 0 }, set x(newX) {}` be `x: number`? What about having a setter but no getter?

**Comment by marijnh** [comment]
That sounds reasonable. The setter but no getter case I don't care much about—we won't have that occur in our API, but treating it just like if they are both there seems like a reasonable way to punt on special-casing it.
